apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nodeapppvc
  namespace: nodeappnamespace

spec:
  accessModes:
    - ReadWriteOnce
      # ReadOnlyMany
      # ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  