apiVersion: v1
kind: Secret

metadata:
  name: nodeappsecret
  namespace: nodeappnamespace

data:
  DB_PORT: MzMwNg==
  DB_USER: YXNhZA==
  DB_PASSWORD: QXNhZDEyMyMj
  DB_NAME: YmxvZ19kYXRhYmFzZQ==
 

#  echo -n "value" |  base64